### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by ms609** [ropensci/treeBASE#12]
Page 8 of the documentation PDF states
for a description of all possible search options, see https://spreadsheets.google.com/pub?key=rL–
O7pyhR8FcnnG5-ofAlw.

This link does not seem to work; I've tried replacing the en-dash with a hyphen, and omitting it.  Has the file been moved or the key been revoked by Google?  Is an up-to-date link available?

**Comment by sckott** [comment]
@ms609 Thanks, will have a look :)

**Comment by sckott** [comment]
This link works for me https://spreadsheets.google.com/pub?key=rL--O7pyhR8FcnnG5-ofAlw 

does it work for you @ms609

**Comment by ms609** [comment]
Yes, it's working for me.
